/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobPreference } from "./JobPreference";
import { JobPreferenceCountArgs } from "./JobPreferenceCountArgs";
import { JobPreferenceFindManyArgs } from "./JobPreferenceFindManyArgs";
import { JobPreferenceFindUniqueArgs } from "./JobPreferenceFindUniqueArgs";
import { DeleteJobPreferenceArgs } from "./DeleteJobPreferenceArgs";
import { JobPreferenceService } from "../jobPreference.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => JobPreference)
export class JobPreferenceResolverBase {
  constructor(
    protected readonly service: JobPreferenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "JobPreference",
    action: "read",
    possession: "any",
  })
  async _jobPreferencesMeta(
    @graphql.Args() args: JobPreferenceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [JobPreference])
  @nestAccessControl.UseRoles({
    resource: "JobPreference",
    action: "read",
    possession: "any",
  })
  async jobPreferences(
    @graphql.Args() args: JobPreferenceFindManyArgs
  ): Promise<JobPreference[]> {
    return this.service.jobPreferences(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => JobPreference, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "JobPreference",
    action: "read",
    possession: "own",
  })
  async jobPreference(
    @graphql.Args() args: JobPreferenceFindUniqueArgs
  ): Promise<JobPreference | null> {
    const result = await this.service.jobPreference(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobPreference)
  @nestAccessControl.UseRoles({
    resource: "JobPreference",
    action: "delete",
    possession: "any",
  })
  async deleteJobPreference(
    @graphql.Args() args: DeleteJobPreferenceArgs
  ): Promise<JobPreference | null> {
    try {
      return await this.service.deleteJobPreference(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
